name: Bump Version

on: 
  workflow_dispatch:
    inputs:
      bumpAction: 
        description: 'Bump action (major, minor, patch)'
        default: ''
        required: true

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

     
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"

      - name: "Bump version"
        run: npm run bump ${{github.event.inputs.bumpAction}}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: "Create PR"
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version
          committer: 0xblock Machine <github-machine-user@0xblock.co>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: bump/version-update-${{ steps.package-version.outputs.current-version }}
          delete-branch: true
          title: '[BUMP] Version update: ${{ steps.package-version.outputs.current-version }}'
          body: |
            Version update to ${{ steps.package-version.outputs.current-version }}
          labels: |
            automated pr
          draft: false